name: Check Fenix announcements

on:
  schedule:
    - cron: "*/1 * * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run bot
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          cd src
          python main.py

      - name: Commit updated state
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add data/state.json

          git commit -m "Update announcement state" || exit 0

          git push